### ISSUE TITLE
Weather did not display

### ISSUE THREAD

**Issue by moookino** [BrainMaestro/cerebro-weather#2]
Hi,

No results shown after trying to search my city

System: 10.12.4 (16E195) macOS Sierra
Version: 0.2.8
![cerebro 2017-04-21 11-12-49](https://cloud.githubusercontent.com/assets/12976657/25271227/b813adda-2683-11e7-942e-b0d196722753.png)

**Comment by BrainMaestro** [comment]
Hey @moookino. Thanks for reporting this.

I unfortunately was not able to reproduce the bug. 
![screen shot 2017-04-21 at 2 33 48 pm](https://cloud.githubusercontent.com/assets/1738373/25279829/acfbf5f8-269f-11e7-8180-a0a5bfeeb867.png)

Maybe it's a network issue? This plugin is unlike the others because it does not display immediately. Basically it tries to wait until you're done typing before showing anything. So if there's a network issue, it would not show anything at all.

If you have more details that could help me reproduce this, that would be much appreciated. Thanks.

**Comment by danielftapiar** [comment]
Same here, doesn't work, left my home City written for a minute, nothing happens.

**Comment by BrainMaestro** [comment]
@SNBSniper. Can you provide more info? Open your devtools and let me know what the error message is. Also which city?

**Comment by moookino** [comment]
Hi @BrainMaestro , found dev tools, here is screenshot with errors i've got, hope it helps
![developer tools - file applications cerebro app contents resources app asar background index html 2017-04-24 12-44-25](https://cloud.githubusercontent.com/assets/12976657/25333750/d9a7bf6c-28eb-11e7-9b00-6da88066ad31.png)

**Comment by BrainMaestro** [comment]
Hey @moookino. Thanks for that. Confirms my suspicion that this issue is the same one as #3. I opened an issue in the main cerebro repo about it. Still looking at it though.

**Comment by BrainMaestro** [comment]
Hey @moookino try installing the new version v1.1.1. Let me know if that fixes it

**Comment by moookino** [comment]
@BrainMaestro fixed for me, thanks for fast feedback 👍
